#!/bin/sh
APP="$( cd "$( dirname "$0" )" && pwd )/.."
SOURCE=$APP/public
BUILD=$APP/public-build

# Clean last build.
rm -rf $BUILD
mkdir $BUILD

# Compress app JS.
cp -a $SOURCE/js $BUILD/js-compressed
find $BUILD/js-compressed -regex ".*\(index\|\(backbone\|collections\|controllers\|helpers\|models\|observers\|shared\|views\)\/\).*js" -exec java -jar $SOURCE/yuicompressor.jar -o {} {} \;

# Combine JS based on configured dependencies.
r.js -o $BUILD/js-compressed/app.build.js

# Combine and compress CSS.
mkdir $BUILD/css
cat \
  $SOURCE/css/bootstrap.css \
  $SOURCE/css/jquery-ui.css \
  $SOURCE/css/jquery-ui-timepicker-addon.css \
  $SOURCE/css/index.css \
  > $BUILD/css/all-full.css
java -jar $SOURCE/yuicompressor.jar -o $BUILD/css/all.css $BUILD/css/all-full.css

# Copy jquery-ui-timepicker-addon images.
cp -a $SOURCE/css/images $BUILD/css/

# Copy app/Bootstrap images.
cp -a $SOURCE/img $BUILD/
