#!/bin/sh
APP="$( cd "$( dirname "$0" )" && pwd )/../"
SOURCE=$APP/public
BUILD=$APP/public-build

# Clean last build.
rm -rf $BUILD

# Combine JS.
r.js -o $SOURCE/js/app.build.js

# Combine and compress CSS.
mkdir $BUILD/css
cat \
  $SOURCE/css/bootstrap.css \
  $SOURCE/css/jquery-ui.css \
  $SOURCE/css/jquery-ui-timepicker-addon.css \
  $SOURCE/css/index.css \
  > $BUILD/css/all-full.css
java -jar $SOURCE/yuicompressor.jar $BUILD/css/all-full.css > $BUILD/css/all.css

# Copy jquery-ui-timepicker-addon images.
cp -a $SOURCE/css/images $BUILD/css/

# Copy app/Bootstrap images.
cp -a $SOURCE/img $BUILD/
